package com.cxgc.front.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2017-8-23 10:55:03 by Hibernate Tools 3.4.0.CR1

/**
 * TAttendanceLog generated by hbm2java
 */
@Entity
@Table(name = "tattendancelog", catalog = "mysql")
public class TAttendanceLog implements java.io.Serializable {

	private int id;
	private String whendo;
	private String whatdo;
	private String whodo;
	private String description;
	private String bz;
	private String data1;
	private String whatthing;

	public TAttendanceLog() {
	}

	public TAttendanceLog(int id) {
		this.id = id;
	}

	public TAttendanceLog(int id, String whendo, String whatdo, String whodo, String description, String bz,
			String data1,String whatthing) {
		this.id = id;
		this.whendo = whendo;
		this.whatdo = whatdo;
		this.whodo = whodo;
		this.description = description;
		this.bz = bz;
		this.data1 = data1;
		this.whatthing=whatthing;
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false, length = 10)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "whendo", length = 255)
	public String getWhendo() {
		return this.whendo;
	}

	public void setWhendo(String whendo) {
		this.whendo = whendo;
	}
	@Column(name = "whatdo", length = 255)
	public String getWhatdo() {
		return this.whatdo;
	}

	public void setWhatdo(String whatdo) {
		this.whatdo = whatdo;
	}

	@Column(name = "whodo", length = 255)
	public String getWhodo() {
		return this.whodo;
	}

	public void setWhodo(String whodo) {
		this.whodo = whodo;
	}

	@Column(name = "description", length = 255)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "bz", length = 255)
	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	@Column(name = "data1", length = 255)
	public String getData1() {
		return this.data1;
	}

	public void setData1(String data1) {
		this.data1 = data1;
	}

	@Column(name = "whatthing", length = 255)
	public String getWhatthing() {
		return whatthing;
	}

	public void setWhatthing(String whatthing) {
		this.whatthing = whatthing;
	}

	
	
}
